# Generated by Django 2.0.13 on 2019-03-23 18:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('English', '英語'), ('Programing', 'プログラミング'), ('Finance', 'ファイナンス')], max_length=10, verbose_name='ジャンル')),
                ('lesson_day', models.DateTimeField(verbose_name='受講日')),
                ('lesson_time', models.PositiveIntegerField(validators=[django.core.validators.MaxLengthValidator(12), django.core.validators.MinLengthValidator(1)], verbose_name='受講時間')),
                ('price', models.PositiveIntegerField(verbose_name='支払金額')),
                ('name', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='school_system.Student', verbose_name='受講者')),
            ],
        ),
    ]
