# Generated by Django 2.0.13 on 2019-03-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_system', '0004_auto_20190323_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonrecord',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='支払金額'),
        ),
    ]
