# Generated by Django 2.0.13 on 2019-03-23 21:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_system', '0007_auto_20190323_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonrecord',
            name='lesson_time',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(12), django.core.validators.MinLengthValidator(1)], verbose_name='受講時間'),
        ),
    ]
